# Generated by Django 5.2.2 on 2025-06-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['id'],
            },
        ),
    ]
