# Generated by Django 5.2.2 on 2025-06-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='componente.componente')),
            ],
        ),
    ]
